"""edit admin column

Revision ID: 08e193944662
Revises: 0024234065e8
Create Date: 2023-07-25 21:20:21.024197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08e193944662'
down_revision = '0024234065e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('admin', 'product_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('product_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###
