"""add individual revenue tables

Revision ID: 3008b9728014
Revises: bbdd10b6ea4f
Create Date: 2024-02-09 13:03:13.902274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3008b9728014'
down_revision = 'bbdd10b6ea4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breadsrevenue',
    sa.Column('br_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('br_id')
    )
    op.create_table('cakesrevenue',
    sa.Column('cr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('cr_id')
    )
    op.create_table('morerevenue',
    sa.Column('mr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('mr_id')
    )
    op.create_table('savouryrevenue',
    sa.Column('sr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('sr_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savouryrevenue')
    op.drop_table('morerevenue')
    op.drop_table('cakesrevenue')
    op.drop_table('breadsrevenue')
    # ### end Alembic commands ###
