"""create ingredient_name

Revision ID: 45d64bb71f01
Revises: e8fab6035e73
Create Date: 2023-07-26 23:56:29.076968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d64bb71f01'
down_revision = 'e8fab6035e73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('ingredient_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'ingredient_name')
    # ### end Alembic commands ###
