"""create details column

Revision ID: 517d29a37f60
Revises: f7e5ceca32ed
Create Date: 2024-02-18 19:25:06.868482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517d29a37f60'
down_revision = 'f7e5ceca32ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_details', sa.TEXT(length=100000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_details')
    # ### end Alembic commands ###
