"""edit stock

Revision ID: 93c541b1f939
Revises: 08e193944662
Create Date: 2023-07-26 13:59:47.693412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93c541b1f939'
down_revision = '08e193944662'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('ingredient_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('stock_ibfk_1', 'stock', type_='foreignkey')
    op.drop_column('stock', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('product_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_foreign_key('stock_ibfk_1', 'stock', 'products', ['product_id'], ['product_id'])
    op.drop_column('stock', 'ingredient_id')
    # ### end Alembic commands ###
