"""create type column

Revision ID: a4cf23fc88be
Revises: 45d64bb71f01
Create Date: 2023-07-31 17:42:07.103337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cf23fc88be'
down_revision = '45d64bb71f01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
