"""new version

Revision ID: b0479ae5520a
Revises: 517d29a37f60
Create Date: 2024-02-22 19:40:49.192405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0479ae5520a'
down_revision = '517d29a37f60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
