"""autoincrement add to products

Revision ID: bd5fe9e49643
Revises: 72fda108cea4
Create Date: 2023-07-26 20:43:46.802187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5fe9e49643'
down_revision = '72fda108cea4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
