"""create productstock table

Revision ID: c3ac15ac5701
Revises: 3008b9728014
Create Date: 2024-02-13 09:01:05.993653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ac15ac5701'
down_revision = '3008b9728014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
