"""create new stock

Revision ID: f7e5ceca32ed
Revises: f8eeda4456d2
Create Date: 2024-02-13 09:25:48.026753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7e5ceca32ed'
down_revision = 'f8eeda4456d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_stock',
    sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.drop_table('product_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_stock',
    sa.Column('product_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('current_stock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minimum_stock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('products_stock')
    # ### end Alembic commands ###
