"""edit id for stock

Revision ID: f8eeda4456d2
Revises: 80d35fa300c9
Create Date: 2024-02-13 09:17:33.223679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8eeda4456d2'
down_revision = '80d35fa300c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_stock', sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('product_stock', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_stock', sa.Column('product_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('product_stock', 'stock_id')
    # ### end Alembic commands ###
